### ISSUE TITLE
Error applying schema

### ISSUE THREAD

**Issue by ioben** [peopledoc/procrastinate#409]
Not 100% sure what's causing this issue, I'm assuming it's an issue with psycopg2 version maybe?

When attempting to apply schema I get the following error:
```
$ procrastinate schema
Applying schema
Error: dict is not a sequence
```

Procrastinate file:
```
import os
import procrastinate as procrastinate_module

procrastinate = procrastinate_module.App(
    connector=procrastinate_module.Psycopg2Connector(**{
        'user': 'app',
        'password': 'password',
        'dbname': 'app',
        'host': os.environ['DATABASE_HOST'], # Uses Node IP
        'port': os.environ['DATABASE_PORT'], # Uses assigned NodePort
    })
)
```

Tried with psycopg2 2.8.6 and 2.9; procrastinate 0.19.0, Python 3.9.5. Digging into the issue with a stacktrace I found that changing [`psycopg2_connector.py:204`](https://github.com/peopledoc/procrastinate/blob/master/procrastinate/psycopg2_connector.py#L204) fixes it (though my solution seems more like a kludge then a fix):
From:
```
cursor.execute(query, self._wrap_json(arguments))
```
To:
```
cursor.execute(query, self._wrap_json(arguments) or None)
```

Any ideas why this might be happening? Seems like a version mismatch is the most likely issue; maybe I could test a known good set of versions to rule that out?

Though I don't think it's relevant, for reproducibility I'm currently using PostgreSQL 12 DB, here's the exact manifest I used to create it in K8s:
```
---
apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  containers:
    - name: postgres
      image: postgres:12
      env:
        - name: POSTGRES_DB
          value: app
        - name: POSTGRES_USER
          value: app
        - name: POSTGRES_PASSWORD
          value: password
      ports:
        - containerPort: 5432
          name: postgresdb
      readinessProbe:
        exec:
          command: ["bash", "-c", "psql -U$POSTGRES_USER -d$POSTGRES_DB -c 'SELECT 1'"]
        initialDelaySeconds: 3
        timeoutSeconds: 20
      livenessProbe:
        exec:
          command: ["bash", "-c", "psql -U$POSTGRES_USER -d$POSTGRES_DB -c 'SELECT 1'"]
        initialDelaySeconds: 3
        timeoutSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: postgresdb
```
